#!/usr/bin/env node
/**
 * Build the self-contained @scale/plugin payload.
 *
 * Produces, inside packages/plugin/:
 *   bin/scale.mjs   — the entire `scale` CLI bundled into one ESM file (every
 *                     dependency inlined: @scale/core, commander, zod, yaml,
 *                     @anthropic-ai/sdk). Needs no node_modules.
 *   bin/scale       — POSIX shell launcher (kept executable) that execs the bundle.
 *   web-dist/       — the built web SPA (`scale serve` serves it).
 *
 * With the plugin's bin/ on PATH (Claude Code adds it automatically when the
 * plugin is enabled), a bare `scale <args>` runs the bundle — zero monorepo
 * dependence. Run `npm run build:plugin` to regenerate after CLI/web changes.
 */
import { build } from 'esbuild';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import fs from 'node:fs';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const PLUGIN = resolve(ROOT, 'packages', 'plugin');
const run = (cmd, args) =>
  execFileSync(cmd, args, { cwd: ROOT, stdio: 'inherit' });

/**
 * Resolve the plugin version, refusing to build if the three manifests disagree.
 *
 * Claude Code caches an installed plugin under a path keyed by this version, so
 * `claude plugin update` is a no-op whenever the version has not moved: a stale
 * cache then silently serves old skills and an old bundle while the repo looks
 * correct. Three files have to agree for a release to be coherent, they are easy
 * to bump partially, and nothing else checks them — so the build does.
 */
function resolveVersion() {
  const readJson = (p) => JSON.parse(fs.readFileSync(p, 'utf8'));
  const sources = [
    ['packages/plugin/.claude-plugin/plugin.json', readJson(resolve(PLUGIN, '.claude-plugin', 'plugin.json')).version],
    ['packages/plugin/package.json', readJson(resolve(PLUGIN, 'package.json')).version],
    ['.claude-plugin/marketplace.json', readJson(resolve(ROOT, '.claude-plugin', 'marketplace.json')).metadata?.version],
  ];
  const [[, version]] = sources;
  const disagree = sources.filter(([, v]) => v !== version);
  if (typeof version !== 'string' || !version) {
    console.error('build:plugin — packages/plugin/.claude-plugin/plugin.json has no version.');
    process.exit(1);
  }
  if (disagree.length > 0) {
    console.error(`build:plugin — plugin version mismatch (expected "${version}"):`);
    for (const [file, v] of sources) console.error(`    ${v === version ? ' ' : '✗'} ${file}: ${v ?? '(missing)'}`);
    console.error('  All three must match, or an installed plugin cache can never be refreshed.');
    process.exit(1);
  }
  return version;
}

const VERSION = resolveVersion();

// 1. Build @scale/core + @scale/cli (tsc) so esbuild can resolve @scale/core's
//    compiled entry, and @scale/web (vite) so we have a dist to copy.
console.log('build:plugin — compiling packages (tsc) + web (vite)…');
run('npm', ['run', 'build']);
run('npm', ['run', 'build', '-w', '@scale/web']);

// 2. Bundle the CLI into ONE self-contained ESM file. The createRequire banner
//    lets bundled CJS deps (e.g. commander) do dynamic `require('node:events')`
//    under ESM; __dirname/__filename are shimmed for any dep that reads them.
console.log('build:plugin — bundling CLI → bin/scale.mjs…');
await build({
  entryPoints: [resolve(ROOT, 'packages', 'cli', 'src', 'index.ts')],
  outfile: resolve(PLUGIN, 'bin', 'scale.mjs'),
  bundle: true,
  platform: 'node',
  format: 'esm',
  packages: 'bundle', // inline ALL deps (nothing left external but node: builtins)
  // Stamp the version INTO the bundle so `scale --version` reports the plugin
  // release it came from. That is the only way to tell, from a running install,
  // whether Claude Code is serving a stale cached copy.
  define: { __SCALE_VERSION__: JSON.stringify(VERSION) },
  banner: {
    js: [
      // Marks the bundle machine-generated. `scale estimate` skips files carrying
      // this so a committed build artifact can't inflate the repo's LOC count —
      // this one file is ~30k lines, several times the real source.
      `// @generated by scripts/build-plugin.mjs (scale v${VERSION}) — do not edit\n`,
      "import{createRequire as __createRequire}from'node:module';",
      "import{fileURLToPath as __fileURLToPath}from'node:url';",
      "import{dirname as __pathDirname}from'node:path';",
      'const require=__createRequire(import.meta.url);',
      'const __filename=__fileURLToPath(import.meta.url);',
      'const __dirname=__pathDirname(__filename);',
    ].join(''),
  },
});

// 3. Keep the shell launcher executable (git may not preserve the bit on all
//    checkouts / it is regenerated infrastructure).
fs.chmodSync(resolve(PLUGIN, 'bin', 'scale'), 0o755);

// 4. Copy the built web SPA → packages/plugin/web-dist (self-contained serve).
const webDistSrc = resolve(ROOT, 'packages', 'web', 'dist');
const webDistDst = resolve(PLUGIN, 'web-dist');
console.log('build:plugin — copying web/dist → web-dist…');
fs.rmSync(webDistDst, { recursive: true, force: true });
fs.cpSync(webDistSrc, webDistDst, { recursive: true });

console.log('build:plugin — done. Self-contained plugin at packages/plugin/');
